adl script improved

diff --git a/pbs/adl b/pbs/adl
--- a/pbs/adl
+++ b/pbs/adl
@@ -1,5 +1,25 @@
 #!/bin/bash
 
+if [ $# != 2 ]; then
+ 
+   echo Expecting 2 arguments.
+ 
+   exit 1
+ 
+fi
+
+m=$1
+
+form=$2
+
+if [ $form != atlas ] && [ $form != nessy ]; then
+
+    echo "format is not recognized. abort."
+
+    exit 1
+
+fi
+
 dir=$(pwd)
 
 IFS='/' read -r -a array <<< "$dir"
@@ -9,8 +29,6 @@ reverse=$(echo "${array[@]} " | tac -s ' ')
 r=($reverse)
 
 declare -i n m idx
-
-m=$1
 
 n=m-1
 
@@ -26,7 +44,9 @@ for i in $(seq 0 $n); do
 
 done
 
-echo $path
+#echo $path/atms/$form
+echo $path/
 
 #rsync -ar --info=progress2 rtagirov@ph-rtagirov.ph.ic.ac.uk:/mnt/SSD/sim/runs/cpline/${r[2]}/${r[1]}/${r[0]}/atms/ ./
-rsync -ar --info=progress2 rtagirov@ph-rtagirov.ph.ic.ac.uk:$path/atms/ ./
+#rsync -ar --info=progress2 rtagirov@ph-rtagirov.ph.ic.ac.uk:$path/atms/$form ./
+rsync -ar --info=progress2 rtagirov@ph-rtagirov.ph.ic.ac.uk:$path/ ./
